import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Testing project by bijay",
  description: "Generated by Testing project by bijay",
  openGraph: {
    title: "OpenGraph Testing project by Bijay",
    description: "OpenGraph Generated by Testing project by Bijay",
    images: [
      {
        url: "/assets/testing_image.jpg",
        width: 600,
        height: 600,
        alt: "Description of the image",
      },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
